//指定的当前proto语法的版本, 有2和3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: GrpcHttpStandard.proto

//import "google/api/annotations.proto";

//包名 服务名称 用于http2路由

package GrpcHttpStandard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 下标的偏移量 用于在字节流中定位准确数据
type SubscriptOffsets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartIndex int64 `protobuf:"varint,1,opt,name=startIndex,proto3" json:"startIndex,omitempty"` // 开始下标
	EndIndex   int64 `protobuf:"varint,2,opt,name=endIndex,proto3" json:"endIndex,omitempty"`     // 结束下标
}

func (x *SubscriptOffsets) Reset() {
	*x = SubscriptOffsets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscriptOffsets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptOffsets) ProtoMessage() {}

func (x *SubscriptOffsets) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptOffsets.ProtoReflect.Descriptor instead.
func (*SubscriptOffsets) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptOffsets) GetStartIndex() int64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *SubscriptOffsets) GetEndIndex() int64 {
	if x != nil {
		return x.EndIndex
	}
	return 0
}

// 布尔值
type Boole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boole bool `protobuf:"varint,1,opt,name=boole,proto3" json:"boole,omitempty"`
}

func (x *Boole) Reset() {
	*x = Boole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boole) ProtoMessage() {}

func (x *Boole) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boole.ProtoReflect.Descriptor instead.
func (*Boole) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{1}
}

func (x *Boole) GetBoole() bool {
	if x != nil {
		return x.Boole
	}
	return false
}

// 状态,用于表示函数执行状态，服务或对象状态
type ProcessingStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Boole bool   `protobuf:"varint,1,opt,name=boole,proto3" json:"boole,omitempty"` // 布尔值
	Info  string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`    // 描述信息
}

func (x *ProcessingStatus) Reset() {
	*x = ProcessingStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessingStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessingStatus) ProtoMessage() {}

func (x *ProcessingStatus) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessingStatus.ProtoReflect.Descriptor instead.
func (*ProcessingStatus) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessingStatus) GetBoole() bool {
	if x != nil {
		return x.Boole
	}
	return false
}

func (x *ProcessingStatus) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

// 名称 String类型
type Str struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Str) Reset() {
	*x = Str{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Str) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Str) ProtoMessage() {}

func (x *Str) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Str.ProtoReflect.Descriptor instead.
func (*Str) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{3}
}

func (x *Str) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 字节数据
type ByteData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ByteData []byte `protobuf:"bytes,1,opt,name=byteData,proto3" json:"byteData,omitempty"`
}

func (x *ByteData) Reset() {
	*x = ByteData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ByteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteData) ProtoMessage() {}

func (x *ByteData) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteData.ProtoReflect.Descriptor instead.
func (*ByteData) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{4}
}

func (x *ByteData) GetByteData() []byte {
	if x != nil {
		return x.ByteData
	}
	return nil
}

// 一组http请求 (请求和响应)
type HttpReqAndRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Req  *HttpReqData `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	Res  *HttpResData `protobuf:"bytes,2,opt,name=res,proto3" json:"res,omitempty"`
	Info *HttpInfo    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *HttpReqAndRes) Reset() {
	*x = HttpReqAndRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReqAndRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReqAndRes) ProtoMessage() {}

func (x *HttpReqAndRes) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReqAndRes.ProtoReflect.Descriptor instead.
func (*HttpReqAndRes) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{5}
}

func (x *HttpReqAndRes) GetReq() *HttpReqData {
	if x != nil {
		return x.Req
	}
	return nil
}

func (x *HttpReqAndRes) GetRes() *HttpResData {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *HttpReqAndRes) GetInfo() *HttpInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// http 单个请求 包含头部和体
type HttpReqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data           []byte          `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`                     //请求包完整报文
	Url            string          `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`                       //请求url
	BodyIndex      int64           `protobuf:"varint,3,opt,name=BodyIndex,proto3" json:"BodyIndex,omitempty"`          //请求体开始下标,如若请求体下标与总长度一致就是没有请求体
	HttpVersion    string          `protobuf:"bytes,4,opt,name=httpVersion,proto3" json:"httpVersion,omitempty"`       // http版本
	HttpReqService *HttpReqService `protobuf:"bytes,5,opt,name=httpReqService,proto3" json:"httpReqService,omitempty"` // 目标信息
}

func (x *HttpReqData) Reset() {
	*x = HttpReqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReqData) ProtoMessage() {}

func (x *HttpReqData) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReqData.ProtoReflect.Descriptor instead.
func (*HttpReqData) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{6}
}

func (x *HttpReqData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HttpReqData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HttpReqData) GetBodyIndex() int64 {
	if x != nil {
		return x.BodyIndex
	}
	return 0
}

func (x *HttpReqData) GetHttpVersion() string {
	if x != nil {
		return x.HttpVersion
	}
	return ""
}

func (x *HttpReqData) GetHttpReqService() *HttpReqService {
	if x != nil {
		return x.HttpReqService
	}
	return nil
}

// http 单个响应 包含头部和体
type HttpResData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data        []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`              //请求包数据
	StatusCode  int32  `protobuf:"varint,2,opt,name=StatusCode,proto3" json:"StatusCode,omitempty"` //状态码
	BodyIndex   int64  `protobuf:"varint,3,opt,name=BodyIndex,proto3" json:"BodyIndex,omitempty"`   //请求体开始下标,如若请求体下标与总长度一致就是没有请求体
	HttpVersion string `protobuf:"bytes,5,opt,name=httpVersion,proto3" json:"httpVersion,omitempty"`
}

func (x *HttpResData) Reset() {
	*x = HttpResData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResData) ProtoMessage() {}

func (x *HttpResData) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResData.ProtoReflect.Descriptor instead.
func (*HttpResData) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{7}
}

func (x *HttpResData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HttpResData) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResData) GetBodyIndex() int64 {
	if x != nil {
		return x.BodyIndex
	}
	return 0
}

func (x *HttpResData) GetHttpVersion() string {
	if x != nil {
		return x.HttpVersion
	}
	return ""
}

// http 请求主机的信息
type HttpReqService struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port   int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Secure bool   `protobuf:"varint,3,opt,name=secure,proto3" json:"secure,omitempty"` // 是否使用https
}

func (x *HttpReqService) Reset() {
	*x = HttpReqService{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReqService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReqService) ProtoMessage() {}

func (x *HttpReqService) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReqService.ProtoReflect.Descriptor instead.
func (*HttpReqService) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{8}
}

func (x *HttpReqService) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *HttpReqService) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HttpReqService) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

// http信息
type HttpInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // id
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"` // 简述信息
	Tmp  []byte `protobuf:"bytes,3,opt,name=tmp,proto3" json:"tmp,omitempty"`   // 预留类型
}

func (x *HttpInfo) Reset() {
	*x = HttpInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GrpcHttpStandard_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpInfo) ProtoMessage() {}

func (x *HttpInfo) ProtoReflect() protoreflect.Message {
	mi := &file_GrpcHttpStandard_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpInfo.ProtoReflect.Descriptor instead.
func (*HttpInfo) Descriptor() ([]byte, []int) {
	return file_GrpcHttpStandard_proto_rawDescGZIP(), []int{9}
}

func (x *HttpInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HttpInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HttpInfo) GetTmp() []byte {
	if x != nil {
		return x.Tmp
	}
	return nil
}

var File_GrpcHttpStandard_proto protoreflect.FileDescriptor

var file_GrpcHttpStandard_proto_rawDesc = []byte{
	0x0a, 0x16, 0x47, 0x72, 0x70, 0x63, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x47, 0x72, 0x70, 0x63, 0x48, 0x74,
	0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x22, 0x4e, 0x0a, 0x10, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1a,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x1d, 0x0a, 0x05, 0x42, 0x6f,
	0x6f, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x22, 0x3c, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x6f, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6f,
	0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x19, 0x0a, 0x03, 0x53, 0x74, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x26, 0x0a, 0x08, 0x42, 0x79, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x79, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x62, 0x79, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x68,
	0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x41, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x03,
	0x72, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x47, 0x72, 0x70, 0x63,
	0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2e, 0x68, 0x74, 0x74,
	0x70, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x71, 0x12, 0x2f, 0x0a,
	0x03, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x47, 0x72, 0x70,
	0x63, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2e, 0x68, 0x74,
	0x74, 0x70, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xbd,
	0x01, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f, 0x64, 0x79, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x42, 0x6f, 0x64, 0x79, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x47,
	0x72, 0x70, 0x63, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x2e,
	0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x0e,
	0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x81,
	0x01, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f, 0x64, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x42, 0x6f, 0x64, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x20, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x0e, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x71, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x22, 0x40, 0x0a, 0x08, 0x68, 0x74, 0x74, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74,
	0x6d, 0x70, 0x42, 0x2d, 0x42, 0x10, 0x47, 0x72, 0x70, 0x63, 0x48, 0x74, 0x74, 0x70, 0x53, 0x74,
	0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x50, 0x01, 0x5a, 0x11, 0x2f, 0x47, 0x72, 0x70, 0x63, 0x48,
	0x74, 0x74, 0x70, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0xa2, 0x02, 0x03, 0x48, 0x4c,
	0x57, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GrpcHttpStandard_proto_rawDescOnce sync.Once
	file_GrpcHttpStandard_proto_rawDescData = file_GrpcHttpStandard_proto_rawDesc
)

func file_GrpcHttpStandard_proto_rawDescGZIP() []byte {
	file_GrpcHttpStandard_proto_rawDescOnce.Do(func() {
		file_GrpcHttpStandard_proto_rawDescData = protoimpl.X.CompressGZIP(file_GrpcHttpStandard_proto_rawDescData)
	})
	return file_GrpcHttpStandard_proto_rawDescData
}

var file_GrpcHttpStandard_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_GrpcHttpStandard_proto_goTypes = []interface{}{
	(*SubscriptOffsets)(nil), // 0: GrpcHttpStandard.SubscriptOffsets
	(*Boole)(nil),            // 1: GrpcHttpStandard.Boole
	(*ProcessingStatus)(nil), // 2: GrpcHttpStandard.processingStatus
	(*Str)(nil),              // 3: GrpcHttpStandard.Str
	(*ByteData)(nil),         // 4: GrpcHttpStandard.ByteData
	(*HttpReqAndRes)(nil),    // 5: GrpcHttpStandard.httpReqAndRes
	(*HttpReqData)(nil),      // 6: GrpcHttpStandard.httpReqData
	(*HttpResData)(nil),      // 7: GrpcHttpStandard.httpResData
	(*HttpReqService)(nil),   // 8: GrpcHttpStandard.httpReqService
	(*HttpInfo)(nil),         // 9: GrpcHttpStandard.httpInfo
}
var file_GrpcHttpStandard_proto_depIdxs = []int32{
	6, // 0: GrpcHttpStandard.httpReqAndRes.req:type_name -> GrpcHttpStandard.httpReqData
	7, // 1: GrpcHttpStandard.httpReqAndRes.res:type_name -> GrpcHttpStandard.httpResData
	9, // 2: GrpcHttpStandard.httpReqAndRes.info:type_name -> GrpcHttpStandard.httpInfo
	8, // 3: GrpcHttpStandard.httpReqData.httpReqService:type_name -> GrpcHttpStandard.httpReqService
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_GrpcHttpStandard_proto_init() }
func file_GrpcHttpStandard_proto_init() {
	if File_GrpcHttpStandard_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GrpcHttpStandard_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscriptOffsets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessingStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Str); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ByteData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpReqAndRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpReqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpReqService); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GrpcHttpStandard_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GrpcHttpStandard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GrpcHttpStandard_proto_goTypes,
		DependencyIndexes: file_GrpcHttpStandard_proto_depIdxs,
		MessageInfos:      file_GrpcHttpStandard_proto_msgTypes,
	}.Build()
	File_GrpcHttpStandard_proto = out.File
	file_GrpcHttpStandard_proto_rawDesc = nil
	file_GrpcHttpStandard_proto_goTypes = nil
	file_GrpcHttpStandard_proto_depIdxs = nil
}
